name: game_ui
description: Game-style UI widgets for Flutter
version: 0.1.0+1
publish_to: none
repository: https://github.com/yakupadakli/game-ui

environment:
  sdk: ^3.11.1
  flutter: ">=3.41.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  assets:
    - assets/images/avatars/
    - assets/images/awards/
    - assets/images/backgrounds/
    - assets/images/balloons/
    - assets/images/buttons/
    - assets/images/characters/
    - assets/images/currencies/
    - assets/images/decorations/
    - assets/images/flags/
    - assets/images/frames/
    - assets/images/icon_buttons/
    - assets/images/icons/common/
    - assets/images/icons/game/
    - assets/images/items/
    - assets/images/labels/
    - assets/images/level_islands/
    - assets/images/level_platforms/
    - assets/images/mascots/bears/
    - assets/images/mascots/elephants/
    - assets/images/mascots/foxes/
    - assets/images/mascots/penguins/
    - assets/images/operations/
    - assets/images/panels/
    - assets/images/spin_wheel/
    - assets/images/streaks/
    - assets/images/toggles/
    - assets/images/treasures/
    - assets/images/xp_bars/

  fonts:
    - family: Fredoka
      fonts:
        - asset: assets/fonts/Fredoka-Variable.ttf
          weight: 300
        - asset: assets/fonts/Fredoka-Variable.ttf
          weight: 400
        - asset: assets/fonts/Fredoka-Variable.ttf
          weight: 500
        - asset: assets/fonts/Fredoka-Variable.ttf
          weight: 600
        - asset: assets/fonts/Fredoka-Variable.ttf
          weight: 700
    - family: BalooChettan2
      fonts:
        - asset: assets/fonts/BalooChettan2-Variable.ttf
          weight: 400
        - asset: assets/fonts/BalooChettan2-Variable.ttf
          weight: 500
        - asset: assets/fonts/BalooChettan2-Variable.ttf
          weight: 600
        - asset: assets/fonts/BalooChettan2-Variable.ttf
          weight: 700
        - asset: assets/fonts/BalooChettan2-Variable.ttf
          weight: 800
